# PostgreSQL database configuration for SocietyGate
# Uses environment variables for credentials (recommended)

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PGUSER")     { "postgres" } %>
  password: <%= ENV.fetch("PGPASSWORD") { "password" } %>
  host:     <%= ENV.fetch("PGHOST")     { "localhost" } %>
  port:     <%= ENV.fetch("PGPORT")     { 5432 } %>

development:
  <<: *default
  database: society_gate_development

test:
  <<: *default
  database: society_gate_test

production:
  <<: *default
  database: society_gate_production
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
  host:     <%= ENV["PGHOST"] %>
  port:     <%= ENV["PGPORT"] %>
